# How to print "Wassup" in Python

In [1]:
print('Wassup')

Wassup


In [1]:
2 + 2

4

In [2]:
answer = 2 + 2

In [3]:
answer

4

In [4]:
answer * 2

8

In [5]:
my_answers = [1, 2, 3, 4]

In [6]:
my_answer

NameError: name 'my_answer' is not defined

In [7]:
my_answers

[1, 2, 3, 4]

In [8]:
my_answers * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
import numpy as np

In [10]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [11]:
my_array = np.array([1, 2, 3, 4])

In [12]:
my_array * 2

array([2, 4, 6, 8])

In [13]:
my_array - 2

array([-1,  0,  1,  2])

In [14]:
my_array.mean()

2.5

In [15]:
my_array.stdev()

AttributeError: 'numpy.ndarray' object has no attribute 'stdev'

In [16]:
my_array.std()

1.118033988749895

In [17]:
my_array.shape

(4,)

In [18]:
import pandas as pd

In [19]:
iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [24]:
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [25]:
iris["sepal.length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [26]:
animal = pd.read_csv("Austin_Animal_Center_Outcomes.csv")

In [27]:
animal

Animal ID        Name                DateTime               MonthYear  \
0        A794011       Chunk  05/08/2019 06:20:00 PM  05/08/2019 06:20:00 PM   
1        A776359       Gizmo  07/18/2018 04:02:00 PM  07/18/2018 04:02:00 PM   
2        A720371       Moose  02/13/2016 05:59:00 PM  02/13/2016 05:59:00 PM   
3        A674754         NaN  03/18/2014 11:47:00 AM  03/18/2014 11:47:00 AM   
4        A689724  *Donatello  10/18/2014 06:52:00 PM  10/18/2014 06:52:00 PM   
...          ...         ...                     ...                     ...   
120545   A823165         NaN  09/17/2020 07:35:00 PM  09/17/2020 07:35:00 PM   
120546   A823167         NaN  09/17/2020 07:35:00 PM  09/17/2020 07:35:00 PM   
120547   A823166         NaN  09/17/2020 07:35:00 PM  09/17/2020 07:35:00 PM   
120548   A823168         NaN  09/17/2020 07:35:00 PM  09/17/2020 07:35:00 PM   
120549   A823016         NaN  09/18/2020 05:03:00 PM  09/18/2020 05:03:00 PM   

       Date of Birth Outcome Type Outcome Subtype Animal Type  \
0         05/02/2017    Rto-Adopt             NaN         Cat   
1         07/12/2017     Adoption             NaN         Dog   
2         10/08/2015     Adoption             NaN         Dog   
3         03/12/2014     Transfer         Partner         Cat   
4         08/01/2014     Adoption             NaN         Cat   
...              ...          ...             ...         ...   
120545    08/25/2020     Transfer         Partner         Cat   
120546    08/25/2020     Transfer         Partner         Cat   
120547    08/25/2020     Transfer         Partner         Cat   
120548    08/25/2020     Transfer         Partner         Cat   
120549    03/14/2020   Euthanasia     Rabies Risk       Other   

       Sex upon Outcome Age upon Outcome                               Breed  \
0         Neutered Male          2 years              Domestic Shorthair Mix   
1         Neutered Male           1 year             Chihuahua Shorthair Mix   
2         Neutered Male         4 months  Anatol Shepherd/Labrador Retriever   
3           Intact Male           6 days              Domestic Shorthair Mix   
4         Neutered Male         2 months              Domestic Shorthair Mix   
...                 ...              ...                                 ...   
120545    Intact Female          3 weeks                  Domestic Shorthair   
120546    Intact Female          3 weeks                  Domestic Shorthair   
120547    Intact Female          3 weeks                  Domestic Shorthair   
120548    Intact Female          3 weeks                  Domestic Shorthair   
120549          Unknown         6 months                             Opossum   

                    Color  
0       Brown Tabby/White  
1             White/Brown  
2                    Buff  
3            Orange Tabby  
4                   Black  
...                   ...  
120545              Black  
120546              Black  
120547              Black  
120548               Blue  
120549         Gray/White  

[120550 rows x 12 columns]