# How to print "Wassup" in Python

In [1]:
print('Wassup')

Wassup


In [1]:
2 + 2

4

In [2]:
answer = 2 + 2

In [3]:
answer

4

In [4]:
answer * 2

8

In [5]:
my_answers = [1, 2, 3, 4]

In [6]:
my_answer

NameError: name 'my_answer' is not defined

In [7]:
my_answers

[1, 2, 3, 4]

In [8]:
my_answers * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
import numpy as np

In [10]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [11]:
my_array = np.array([1, 2, 3, 4])

In [12]:
my_array * 2

array([2, 4, 6, 8])

In [13]:
my_array - 2

array([-1,  0,  1,  2])

In [14]:
my_array.mean()

2.5

In [15]:
my_array.stdev()

AttributeError: 'numpy.ndarray' object has no attribute 'stdev'

In [16]:
my_array.std()

1.118033988749895

In [17]:
my_array.shape

(4,)

In [18]:
import pandas as pd

In [19]:
iris = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [24]:
iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [25]:
iris["sepal.length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [26]:
animal = pd.read_csv("Austin_Animal_Center_Outcomes.csv")

In [3]:
animal

NameError: name 'animal' is not defined

In [1]:
animal.describe()

NameError: name 'animal' is not defined

In [2]:
animal

NameError: name 'animal' is not defined